export const ASCEND_NOTIFICATION_OPTIONS = [
  "Approaching exit altitude",
  "Assess ground speed",
  "Breathe",
  "Check camera",
  "Check comms",
  "Check equipment",
  "Check goggles",
  "Check helmet",
  "Check of 3s",
  "Check oxygen",
  "Check rucksack",
  "Check seat belts",
  "Check static line",
  "Check student",
  "Check weapons",
  "Disconnect oxygen",
  "Exit altitude",
  "Gear check",
  "Goggles",
  "Handle checks",
  "Interview",
  "Meditation",
  "Oxygen required",
  "Pin check",
  "Practice EPs",
  "Review",
  "Seatbelts",
  "Spot",
  "Visualization",
  "Check altitude",
  "Infrared",
  "Silence",
  "Track-away",
  "Check altimeter",
];

export const FREEFALL_NOTIFICATION_OPTIONS = [
  "AFF pull altitude",
  "Alarm 1",
  "Alarm 2",
  "Alarm 3",
  "Angle track",
  "Approaching hard deck",
  "Back flip",
  "Backfly",
  "Backward",
  "Bank",
  "Barrel roll",
  "Belly fly",
  "Breakoff",
  "Campfire",
  "Carve",
  "Check handle",
  "Circle of awareness",
  "Decision altitude",
  "Deploy",
  "Dock",
  "Down",
  "Flatten",
  "Flip over",
  "Forward",
  "Front flip",
  "Handle checks",
  "Hard deck",
  "Head-down",
  "In-facing",
  "Left",
  "Level out",
  "Lock on",
  "Neutral",
  "No more maneuvers",
  "Opening altitude",
  "Out-facing",
  "Pull",
  "Pull altitude",
  "Right",
  "Separate",
  "Side slide",
  "Sitfly",
  "Staged breakoff",
  "Stand",
  "Steeper",
  "Tandem pull altitude",
  "Trace",
  "Track",
  "Turn",
  "Up",
  "Wave-off",
  "Check altitude",
  "Infrared",
  "Silence",
  "Track-away",
  "Check altimeter",
];

export const CANOPY_NOTIFICATION_OPTIONS = [
  "Alarm 4",
  "Alarm 5",
  "Alarm 6",
  "Alarm 7",
  "Alarm 8",
  "Approaching hard deck",
  "Assess ground speed",
  "Base leg",
  "Blackout",
  "Canopy control check",
  "Decision altitude",
  "Disconnect RSL",
  "Downwind leg",
  "Entry point",
  "Final approach",
  "Hard deck",
  "Infrared",
  "Inspect canopy",
  "Lights on",
  "Locate landing area",
  "Lowest cutaway altitude",
  "No low turns",
  "Perform canopy tasks",
  "Practice EPs",
  "Riser turns",
  "Check altitude",
  "Silence",
  "Track-away",
  "Check altimeter",
];
